### ISSUE TITLE
Redirection of Parking Beauvais Nainville not working

### ISSUE THREAD

**Issue by joxad** [boolder-org/boolder-android#114]
<img width="884" alt="image" src="https://github.com/boolder-org/boolder-android/assets/2451982/79bd8f09-298b-4080-8f67-41b8045cd186">

https://github.com/boolder-org/boolder-android/assets/2451982/e31ad27e-2bf4-4888-916c-9efc5268518d

Hello, when we try to go to the parking of Beauvais Nainville, google maps doesn't redirect correctly.
I looked at the code and I think the error is in the googleUrl of the POI which is the parking.
Not sure where it is stored (maybe in the mapbox directly?)

**Comment by nmondollot** [comment]
You're right!
Thank you for the bug report.

I will update the database (on the backend side) with this location: https://maps.app.goo.gl/j4CFuSwHaJxgRXxu5

I will appear in the next app release.

Thanks!
