### ISSUE TITLE
Opening downloaded pictures is slow with bad connection

### ISSUE THREAD

**Issue by karajan9** [boolder-org/boolder-android#152]
Hi there!
I ran into the following problem: 
If I'm in the forest with a bad connection, opening pictures takes multiple seconds -- even though I have downloaded the pictures for that area. In this case switching on offline mode helps (it's also no problem with a really good connection, like at home).
It seems to me the app prefers loading pictures again (if there is any connection at all) instead of using the ones which are already downloaded. 
Would it be possible to check for downloaded pictures _first_ (if that's really the thing I'm observing here)?
Best wishes and thanks for making such an amazing app!

**Comment by nmondollot** [comment]
Good catch!
It's definitely something we can improve, we'll look into it. cc @wang-li 
Thanks for your report 👍

**Comment by wang-li** [comment]
Thank you for reporting this bug @karajan9! 
This should be fixed in the current version (available on the Play store now)
