### ISSUE TITLE
Grade filtering UX

### ISSUE THREAD

**Issue by Tehforsch** [boolder-org/boolder-android#156]
Thanks for the awesome app!

If I press on the grade filter button and select "Custom", the "Min grade" shows 4A and the "Max grade" shows 5A. Intuitively, I feel that in order to set a 6A-6A+ range, for example, I should click on "Min grade" and select 6A which would automatically move the "Max grade" up to 6A. However, the dropdown only shows grades up to 5A because of the "Max Grade" setting. Automatically changing the "Max grade" becomes especially useful if one wants to change the filter to a single grade (i.e. 6A-6A).

The same happens in reverse (cannot set "Max grade" lower than "Min grade").

I hope it's ok to report such a tiny inconvenience, otherwise feel free to close.

**Comment by nmondollot** [comment]
Good catch!
@wang-li what do you think?

> I hope it's ok to report such a tiny inconvenience, otherwise feel free to close.

Of course! We want to fix even the tiny stuff and make the best app as possible.

**Comment by wang-li** [comment]
Hey @Tehforsch, thank you for your feedback! I just merged a commit that implements your suggestion, it will be available in the next release ✌️ 

Ping @nmondollot 🤓
