### ISSUE TITLE
Keyboard does not open upon clicking the search bar

### ISSUE THREAD

**Issue by Tehforsch** [boolder-org/boolder-android#157]
Another tiny UX inconvenience:

After clicking the search bar (the one with hint "Problem or area name"), the android keyboard does not automatically open:

![photo_2024-08-30_15-13-24](https://github.com/user-attachments/assets/d36185a3-9cec-4c0c-9db3-414718998bf7)

I have to click the search bar again for the keyboard to open.
The same happens on the iOS version of the app.

**Comment by nmondollot** [comment]
Good catch!
I created an issue for iOS too https://github.com/boolder-org/boolder-ios/issues/34
