### ISSUE TITLE
Full screen photo

### ISSUE THREAD

**Issue by nmondollot** [boolder-org/boolder-android#21]
When user taps on a topo photo, show a full-screen mode with pinch-to-zoom.

Note: when https://github.com/boolder-org/boolder-android/issues/19 is implemented, make sure that circles are easy to tap and doesn't not trigger the full-screen mode if the tap is a few pixels off.

# Demo iOS

https://github.com/boolder-org/boolder-android/assets/330823/c6870ea3-abfd-4f6d-b12f-a8b7a3a6f359

# Code iOS

https://github.com/boolder-org/boolder-ios/blob/main/Boolder/UI/Map/Problem%20details/Topo/TopoFullScreenView.swift

**Comment by nmondollot** [comment]
Hello Wenjie,

Sorry for the late reply, I was on vacation.

Yes, you can open a PR! 
Or publish your code somewhere else, it's fine. As long as we can see your code.

@wang-li is our lead developer, he will get back to you regarding the other questions!

**Comment by Novmbrain** [comment]
Hi, No worry. I have already forked the repo. I plan to implement the whole spec this week and create a PR for the first review. So glad to be able to contribute to an app that bleausards (include me) use daily
