### ISSUE TITLE
Feature: Boulder lists for a trip

### ISSUE THREAD

**Issue by pallgeuer** [boolder-org/boolder-android#23]
Hi! First of all let me say that I'm a huge fan of this project, and in particular its open-source nature.

I'm using Boolder to help plan an upcoming trip to Fontainebleau, and it struck me that it would be a very useful feature if it were possible to create lists ("tick-list"?) and then add routes to those lists. That means for example I could add 10 boulders or whatever to a list, and then when I go to the area I would filter the displayed boulders to only display those that are on a particular list. Then I know exactly where all my projects are for the day, and which one is closest to where I am right now.

As a possible extension to this idea, it will probably happen from time to time that you want to add a boulder to a list, that isn't present in the database. For such cases it would be cool to be able to long press on the map to add a custom route marker and set a name/grade for it, and maybe even be able to paste a bleau.info URL into the app instead in order to associate the marker with a known bleau.info route and automatically have it retrieve name/grade. This custom-created marker can then be added to a list as normal.

Finally, it would make it visually easier to find listed boulders on the map if the grey marker used a lighter or darker grey as a function of the grade. For example, if the map is currently set up to show routes from a min grade of 6a to a max grade of 7b (filter), then 6a routes would show in very light grey, 7b routes would show up in very dark grey, and every grade inbetween, like 6c would just interpolate the grey brightness linearly between these two.

I think this tick-list feature would make a very unique and powerful selling point for the app.

**Comment by nmondollot** [comment]
Thank you Philipp!

The tick list is already available on iPhone, but not yet on Android. It's high on our roadmap, though.
I'll create a dedicated issue soon to make the specs clearer.

About adding a problem/boulder: it's a bit more tricky, but we're also working on it!
I hope to have something ready for September.

About dark/light grey for grades: it's an interesting idea!
We shipped an update this week to allow filtering by grade, what do you think about it? Do you still think using different colors would help?

**Comment by nmondollot** [comment]
I created a dedicated [issue](https://github.com/boolder-org/boolder-android/issues/28) for the Tick List

Closing this one for now, but feel free to add more suggestions!

**Comment by pallgeuer** [comment]
> Thank you Philipp!
> 
> The tick list is already available on iPhone, but not yet on Android. It's high on our roadmap, though. I'll create a dedicated issue soon to make the specs clearer.
> 
> About adding a problem/boulder: it's a bit more tricky, but we're also working on it! I hope to have something ready for September.
> 
> About dark/light grey for grades: it's an interesting idea! We shipped an update this week to allow filtering by grade, what do you think about it? Do you still think using different colors would help?

Ah great to see that a tick list has already made it to iPhone. Browsing the issues I realised that a number of features were in iPhone but not yet Android due to the lack of an Android developer, but I hadn't seen the tick list feature. Btw is multiple lists (e.g. like on bleau.info) available, or simply a single global "marked" list? Being able to share a tick list to another phone running the Boolder app as well would probably also be quite useful (e.g. your phone battery running out), as well as filtering the map to only show the boulders from certain tick lists (e.g. show your tick list and the one your friend shared with you at the same time).

Also good to hear that adding custom boulder markers has already been thought about.

Yes, I'm already using the version with grade filtering and find that to be a very useful feature (I'm here right now). When I go on a Bleau trip for a week, my workflow would be that I add all the boulders I would consider trying to a new tick list, and then when I'm in the area, I would for clarity filter the map to just show the boulders on the list. In order to decide what next boulder I want to go to though, it would help to have the various shades of grey because then I can immediately tell the difference between a 6A and a 7B, without having to tap on all the dots and without having to change grade filters a few times to see what's around. Basically, it allows me to see with a single glance how many routes of what approximate difficulty are around (while panning through the map).

The reason why I suggested that the colour scale depends on the grade filter settings is so that the colour differences become as clear as possible for the grade range you actually care about. If the minimum grade is 2 and maximum grade is 9a, the difference in colour between 6a and 6c will hardly be visible, but if you filter to just 6a-6c then it will be.

**Comment by nmondollot** [comment]
> Btw is multiple lists (e.g. like on bleau.info) available, or simply a single global "marked" list? Being able to share a tick list to another phone running the Boolder app as well would probably also be quite useful (e.g. your phone battery running out), as well as filtering the map to only show the boulders from certain tick lists (e.g. show your tick list and the one your friend shared with you at the same time).

Very good suggestion!
For now on iPhone it's a single list, but we can improve it in the future.
I love the idea of being able to share a list with someone else.

> In order to decide what next boulder I want to go to though, it would help to have the various shades of grey because then I can immediately tell the difference between a 6A and a 7B, without having to tap on all the dots and without having to change grade filters a few times to see what's around.

Ok I see your point, thanks for the detailed explanation!
On iPhone we decided to display the name + **grade** directly on the map when using a filter (popular, ticked, or favorite)
Would that solve your problem?
You can see it in action [here](https://github.com/boolder-org/boolder-android/issues/24) or in the screenshot below:

<img width="295" alt="Capture d’écran 2023-07-25 à 16 26 48" src="https://github.com/boolder-org/boolder-android/assets/330823/d06e4898-8acf-4343-b31e-7c99f9da59d5">

Using shades of grey is pretty smart too, but I'm afraid that it will make the map hard to read (grey isn't the best color to have good contrast 😬 )

**Comment by pallgeuer** [comment]
I agree, being able to share or export a list could be useful in many situations.

Name + grade I think solves the problem even better than shades of grey, if shades of grey makes for bad readability.
