### ISSUE TITLE
Tick list

### ISSUE THREAD

**Issue by nmondollot** [boolder-org/boolder-android#28]
- Allow users to mark a problem as "ticked" or as a "favorite".
- Add a tab in the app to display the list of ticks and favorites (and tap on a problem to see it on the map)

# Demo iOS

https://github.com/boolder-org/boolder-android/assets/330823/b5ef131f-6b0b-47eb-b4f9-ef38f7a59c3f

https://github.com/boolder-org/boolder-android/assets/330823/b5d59f58-7bda-4a6e-8db6-8a2e0fd53dfb

# Data model

Let's store the data locally on disk (on iOS we use a separate sqlite database via CoreData) with the following schema:

Ticks:
- `id` (optional)
- `problemId`
- `createdAt`

Favorites:
- `id` (optional)
- `problemId`
- `createdAt`

# Code iOS

https://github.com/boolder-org/boolder-ios/blob/b418c9d55501a911de4b49b6b2a8b8d51ae2c403/Boolder/UI/Tick%20List/TickList.swift

https://github.com/boolder-org/boolder-ios/blob/b418c9d55501a911de4b49b6b2a8b8d51ae2c403/Boolder/UI/Map/Problem%20details/ProblemDetailsView.swift#L199-L219

https://github.com/boolder-org/boolder-ios/blob/b418c9d55501a911de4b49b6b2a8b8d51ae2c403/Boolder/UI/Map/Problem%20details/ProblemDetailsView.swift#L277-L364

**Comment by pallgeuer** [comment]
Would it be useful to have a different outline circle colour depending on whether a route is marked as "projet" or "reussi"?

**Comment by nmondollot** [comment]
> Would it be useful to have a different outline circle colour depending on whether a route is marked as "projet" or "reussi"?

Good question!
I did a test last year, but the result wasn't great (the map was hard to read)

On iOS we've gone another route: we use a filter for ticks ("réussi") and favorites ("projet").
We'll probably do the same on Android once the Tick List is live.

**Comment by mirrom** [comment]
Have you thought about integrating [Apple's CloudKit](https://developer.apple.com/icloud/cloudkit/) into the app? That would enable you to store the tick lists and projects in the users' iCloud so they are synced between multiple devices and are not lost if you have to change your device.

**Comment by nmondollot** [comment]
> Have you thought about integrating [Apple's CloudKit](https://developer.apple.com/icloud/cloudkit/) into the app? That would enable you to store the tick lists and projects in the users' iCloud so they are synced between multiple devices and are not lost if you have to change your device.

Good question!
Storing the data on-device is only step 1.
Step 2 will be to store data on a boolder account (server-side) => it's on the long-term roadmap 😎 

> Ooops, this is the Android repo, sorry! But for iOS the CloudKit would still be a nice enhancement :)

Haha :)
Yes you're right, it could a nice enhancement for the short term (at least for iOS).
I'll add it to the todo list.

Thanks for the suggestion!
