### ISSUE TITLE
"Enregistrer" button on android version

### ISSUE THREAD

**Issue by linogaliana** [boolder-org/boolder-android#8]
I discovered boolder recently and I I liked it a lot. 

I saw that my friend that uses the IOS version has a feature that mine (android) does not have : you can save a Block as project or save it as completed. 

Is there any plan to integrate that nice feature on the android version ? 

(If I could I would make a PR but I guess my python skills are not very useful for mobile phone apps 😀)

**Comment by nmondollot** [comment]
Thanks for your feedback!

Yes, that's the plan :)
We're currently missing an Android developer, though.
If you know someone or want to contribute yourself, let me know!

**Comment by nmondollot** [comment]
We'll focus on #6 and #5 first.
Closing this issue for now.
